apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include 'fastapi.fullname' . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include 'fastapi.name' . }}
  template:
    metadata:
      labels:
        app: {{ include 'fastapi.name' . }}
    spec:
      containers:
      - name: fastapi
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        ports:
        - containerPort: 8000
